module.exports.config = {
  name: "horny",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Romim",
  description: "horny video",
  usePrefix: false,
  commandCategory: "Hình ảnh",
  usages: "uff",
  cooldowns: 00,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};

module.exports.run = async({api,event,args,client,Users,Threads,__GLOBAL,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
   var hi = [" 𓆩𓆪᭄𓆩「 ✫𝙷𝙾𝚁𝙽𝚈 𝚅𝙸𝙳𝙴𝙾 𝙱𝚈 𝚁4𝙼1𝙼 ✭  」⁾"];
  var know = hi[Math.floor(Math.random() * hi.length)];
  var link = [

  "https://drive.google.com/uc?id=1ABtEvo3Cvls7pkA4e937k9aNAL_YJc8Q",
  "https://drive.google.com/uc?id=1AFXbiWAIh90KQOqVYxHWHmv-3NKmJ76a",
  "https://drive.google.com/uc?id=1AB6SN7vCf7CD1sKiklfPHZOCzf3x8iLG",
  "https://drive.google.com/uc?id=1AC3BNRdKYOMAAS1lhu91PMkY27C0woVH",
  "https://drive.google.com/uc?id=1ACc1GddqGYPo80E4vStBvqVXA7FcdMlS",
  "https://drive.google.com/uc?id=1A67KkN-FThrW1O79ZxqioBnvvpaDVgfT", 
  "https://drive.google.com/uc?id=1A8YWpc7a1n-aDGSoQeGNO8gGphtj-HBl",
  "https://drive.google.com/uc?id=1BKjLsM7owAO97f8R3hlSjTUgKZ2lVn6c",
  "https://drive.google.com/uc?id=1AQRYq6PPWpiUY7lpLvMy3gXvGOWmSlSs",
  "https://drive.google.com/uc?id=1BSrpsS5-9UaumBTdY6ixqXJBTP2-PxvM",
  "https://drive.google.com/uc?id=19PIfqFwxPx93nFAMuo1w8RxvdpVOfq7j",
  "https://drive.google.com/uc?id=196GS-0a1HOGF5qOel3P7AC0rPEGgognO",
  "https://drive.google.com/uc?id=19-UI5cf2l3E4KXZ69Ts2wue92tdZLb0d",
  "https://drive.google.com/uc?id=1AKLgQKT7Dr-LFWynOlA4lDN-ySPkDOD8",
  "https://drive.google.com/uc?id=192rfTydqFBuqffcLqdAalM-lX06RWArY",
  "https://drive.google.com/uc?id=1AEqPO50O1eanOMIOwzIZrnsdYk3M3-Q7",
  "https://drive.google.com/uc?id=1BRyantlhCTiu74LQG2f_PrJnRpkbUaUI",
  "https://drive.google.com/uc?id=19geIE0T2JrI3FV1jUrT6KxFSyrxrAXaQ",
  "https://drive.google.com/uc?id=19qUOL6usIDDO9HyzgwA4GS84b1fn43KX",
  "https://drive.google.com/uc?id=19O390CZ84TAibBs-ia-V15KrJS2ia2u4",
  "https://drive.google.com/uc?id=1BA6o7VFYy5sf92o1_gQJQn7y8LTNhuWr",
  "https://drive.google.com/uc?id=1BulVr8xplV69FbkF2RkibuM5qGXqsAtO",
  "https://drive.google.com/uc?id=18qb8fMubr2U5PPI7KJ3q45T-oNXI5oOB",
  "https://drive.google.com/uc?id=1A0RSYaykjcpUBnc8vGQHdShULj-M8vxF",
  "https://drive.google.com/uc?id=18a_Y0AFxdFadgjaTqCNcgkUidvwyIoSh",
  "https://drive.google.com/uc?id=1BSHYwtZNTIlTFqIIhddwYkxy5yWfJhH7",
  "https://drive.google.com/uc?id=19OWbsQ01CK7-waMYHBwIL2iPeCuV9Fi4",
  "https://drive.google.com/uc?id=19NJRYXib7JGJhWuKFDCONbfVvnMLw7h8",
  "https://drive.google.com/uc?id=19F6ZTSXDE6UTHXmdOzu7KoWDn7CjHP3v",
  "https://drive.google.com/uc?id=19zTnXe0H2TRp2vtjAjNQeO8FNg_WA4DE",
  "https://drive.google.com/uc?id=19ibqiqQziTwG39_rnadLw_RlR8iTsKja",
  "https://drive.google.com/uc?id=18dN7BgO2LvxtA4uYjNS1ujN4xNHCSckD",
  "https://drive.google.com/uc?id=19krxxa6N7YYBpZf9cGZtLjvTKDzpLFIl",
  "https://drive.google.com/uc?id=1B5OcYmB6l1POe7iAG2jKbk9cJYRK3uaR",
  "https://drive.google.com/uc?id=1BaeV1dSUEb6PWWrUur5CUjiyH-0tWMgQ",
  "https://drive.google.com/uc?id=19Ut381EDTdjYPRnPvy3pQq6oyQ5Y8bq3",
  "https://drive.google.com/uc?id=1BwWdiggrcPRemz3UHtQZ8PxBSexLY_cp",
  "https://drive.google.com/uc?id=1ARSdgb82oP6DsIUi-YxDaZu-XSMOJdz1",
  "https://drive.google.com/uc?id=19A4UI8fCQnFd1Z3aONYNrf2jYsCcoFn4",
  "https://drive.google.com/uc?id=1C2ZX7bRSM04DZ9tKTT3l4oj4Qi2Fbkdt",
  "https://drive.google.com/uc?id=1A1zlmgOTsPoJHmyXDm4T49cmjSbTLgg0",
  "https://drive.google.com/uc?id=18tOHBnG_vrnG_io6Kgj1LPI36-7mDsBy",
  "https://drive.google.com/uc?id=19fhL4nvaVT2ehz93W0DPRVocrczSljaF",
  "https://drive.google.com/uc?id=1AixGc0pxlmpmgHYu5wAbDlYHv2whRqDg",
  "https://drive.google.com/uc?id=1BMuw5bV5I100iACo52fGujoL5vQDlRVA",
  "https://drive.google.com/uc?id=1BenMV3N13x80P-hEG4G8u5opRxm6Vlfc",
  "https://drive.google.com/uc?id=1AUlNoTFOWKSFhRPpjv1KCv48MGpd8r0C",
  "https://drive.google.com/uc?id=1AIeMHRnwQ0SUN0TiPQ32UHyx9eL9cicL",
  "https://drive.google.com/uc?id=1BAMLpNMZQaHhWNKIsjCDFAdTnQvhuQh7",
  "https://drive.google.com/uc?id=1BoUF2w17L9XGnqlqG3JibQr7iP7Anmqs",
  "https://drive.google.com/uc?id=1Bk_ITSsW_RAVKniu69RYVMpqZAT7kABl",
  "https://drive.google.com/uc?id=19erDLH1W5-rOvUHOBNpg0Ur0lS3O88a8",
  "https://drive.google.com/uc?id=1A-yFTjlvltRjyDZEnyQrpmZsYgLQRTbi",
  "https://drive.google.com/uc?id=192VVIzLzmh4hTekLiL_7PeleZUCs5uj3",
  "https://drive.google.com/uc?id=19TcB5dAvlS3-47WWFKvXgZrNlG7l0r0o",
  "https://drive.google.com/uc?id=19gPSfV0_Dx1tE8bOYciUICS7Wk9h4x-l",
  "https://drive.google.com/uc?id=1AHFuEHZ2NhYPaiZDAQZVvZHHuu1DQR13",
  "https://drive.google.com/uc?id=1AcGr8oNrQUxpO8FTBvypImLJu6u0Nehh",
  "https://drive.google.com/uc?id=19cTN8R1si-0a-2HHRl51531B9LeUVGgi",
  "https://drive.google.com/uc?id=1BC7jTudYN-6_BKks4GZwjK3CDFKNtftG",
  "https://drive.google.com/uc?id=19TBwM2CfPgzZ7bNOtbnQxptwHEn03stv",
  "https://drive.google.com/uc?id=1BR50XoBRpCv1oN9WrfPTYx8fNWjSy0Ql",
  "https://drive.google.com/uc?id=1M4YeRqZ1wVqTl5h0Flg8TfAteKF8qxXv",
  "https://drive.google.com/uc?id=1L0RORmTLGjdiFkxe-Ughm4ro5dT7Bxnb",
  "https://drive.google.com/uc?id=1L-cMnAv5xNDCq9qpX1Wmd9DNqXY_3JZ4",
  "https://drive.google.com/uc?id=1L6QaRPAB5n8DI9LWx-gN-EiIWum5kXsi",
  "https://drive.google.com/uc?id=1LW26ziDHgdwM7kQMA5Cfpk3csJlZKRGb",
  "https://drive.google.com/uc?id=1Kt1d3_OJ1IAv74oFRoOsyCcGTFNfTjbk",
  "https://drive.google.com/uc?id=1LzbovombmjesEk9xztdTJWgjYAhy97tX",
  "https://drive.google.com/uc?id=1Lwdjx3iTptlxCHE-ur9BeA4AwqM49ZPB",
  "https://drive.google.com/uc?id=1KqoLbCteyl5jHToocXMTlxNoFkwNJaLZ",
  "https://drive.google.com/uc?id=1L4YWTlFlz9xySybnoMGj3EO245uev260",
  "https://drive.google.com/uc?id=1L_LTO49afpWcZkYFbx5YHFYoX92WqXDs",
  "https://drive.google.com/uc?id=1Ks-zPX8qmY1Cn93CB_WJfo-jrODP7CCA",
  "https://drive.google.com/uc?id=1M2v1QefI9IUNmLCtrgcF7iD6VrQnR7eq",
  "https://drive.google.com/uc?id=1LdrAw2lasqvNItoCVCU-SnYxrMwkFL9-",
  "https://drive.google.com/uc?id=1Kx8pk3V4ADNIcUa-AC0CEVCfdtqxRvIA",
  "https://drive.google.com/uc?id=1Lo99PlWTVxTZjCfLQpOwPQtSxfejy5-l",
  "https://drive.google.com/uc?id=1LmUCqRhLb3d6WzBSz7zdq1tzJyS0umup",
  "https://drive.google.com/uc?id=1LCc0pVHqQdAS9oHyDVXDDjPjdV2aC4nq",
  "https://drive.google.com/uc?id=1Li-3JVP5Hm2_sAw5nxJQZ-XeqjnpgEdo",
  "https://drive.google.com/uc?id=1LuNEIy5Kyl8gpPwTxjTpo5dmVWri6eFH",
  "https://drive.google.com/uc?id=1LFmnkvf0DhNf-g_jsWDLFkV6ksD0Rd1P",
  "https://drive.google.com/uc?id=1LdrjkMYoPt_QzeGKTekGRQ5EvvYTwbnl",
  "https://drive.google.com/uc?id=1M0V2iXurZs5Qr-rW_MZsBDrdNv3s1JJG",
];
     var callback = () => api.sendMessage({body:`「 ${know} 」`,attachment: fs.createReadStream(__dirname + "/cache/15.mp4")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/15.mp4"));    
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/15.mp4")).on("close",() => callback());
   };